# Generated by Django 3.0.7 on 2020-09-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
