# Generated by Django 3.0.7 on 2020-09-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='initial_severity',
            field=models.CharField(choices=[('mi', 'Mild'), ('mo', 'Moderate'), ('s', 'Severe'), ('f', 'Fatal')], default='m', max_length=2),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(choices=[('ch', 'Corporate Headoffice'), ('od', 'Operations Department'), ('ws', 'Work Station'), ('ms', 'Marketing Division')], default='ch', max_length=6),
        ),
    ]
