# Generated by Django 3.0.7 on 2020-09-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentreporting', '0002_auto_20200926_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='initial_severity',
            field=models.CharField(choices=[('mi', 'Mild'), ('mo', 'Moderate'), ('s', 'Severe'), ('f', 'Fatal')], default='mo', max_length=2),
        ),
        migrations.AlterField(
            model_name='incident',
            name='sub_incident_types',
            field=models.CharField(max_length=100),
        ),
    ]
